// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-05
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.1"
vTitle                          = "Williams %R"
vShort                          = "W%R"
vOverlay                        = false
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vSource                         = input( defval = close, type = input.source, title = "Source" )
vLength                         = input( defval = 10, minval = 1, maxval = 1024, title = "Length" )
vSmooth                         = input( defval = 1, minval = 1, maxval = 1024, title = "Smooth" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, le ) =>
    r = float( 0 )
    for i = n + 0 to ( n + ( le - 1 ) )
        r := ( r + s[ i ] )
    a = r / le

fWpR( n, s, le ) =>
    r = float( 0 )
    r := ( ( highest( high[ n ], le ) - s[ n ] ) / ( highest( high[ n ], le ) - lowest( low[ n ], le ) ) * -100 )

//-------------------------------------
// COLORS

fColor( n, s ) =>
    r = ( s[ n + 1 ] < s[ n ] ) ? #26A69A : #EF5350
    r

//-------------------------------------
// PLOT

vWpR                            = fMa( 0, fWpR( 0, vSource, vLength ), vSmooth )
vPlotWpR                        = plot( vWpR, style = plot.style_line, color = fColor( 0, vWpR ), title = "W%R" )

//-------------------------------------
// BANDS

vUpperBand                      = hline( -80, color = color.black, title = "Upper Band" )
vLowerBand                      = hline( -20, color = color.black, title = "Lower Band" )

//-------------------------------------