// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-04
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.1"
vTitle                          = "Momentum"
vShort                          = "MOM"
vOverlay                        = false
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vSource                         = input( defval = close, type = input.source, title = "Source" )
vLength                         = input( defval = 10, minval = 1, maxval = 1024, title = "Length" )
vSmooth                         = input( defval = 1, minval = 1, maxval = 1024, title = "Smooth" )
vOffSet                         = input( defval = 0, minval = 0, maxval = 1024, title = "Offset" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, le ) =>
    r = float( 0 )
    for i = n + 0 to ( n + ( le - 1 ) )
        r := ( r + s[ i ] )
    a = r / le

fMom( n, s, le ) =>
    r = float( 0 )
    r := ( s[ n ] - s[ n + le ] )

//-------------------------------------
// COLORS

fColor( n, s ) =>
    r = ( s[ n ] >= 0 ) ? ( s[ n + 1 ] < s[ n ] ) ? #26A69A : #B2DFDB : ( s[ n + 1 ] > s[ n ] ) ? #EF5350 : #FFCDD2
    r

//-------------------------------------
// PLOT

vLineMedian                     = hline( 0, color = #666666, linestyle = hline.style_dashed, linewidth = 1, title = "Median", editable = true )

vMom                            = fMa( 0, fMom( vOffSet, vSource, vLength ), vSmooth )
vPlotMom                        = plot( vMom, style = plot.style_histogram, linewidth = 4, color = fColor( 0, vMom ), title = "Momentum" )

//-------------------------------------