// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-05
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.0"
vTitle                          = "Exponential Moving Average"
vShort                          = "EMA"
vOverlay                        = true
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vEmaSource                      = input( defval = close, title = "EMA - Source" )
vEmaLength                      = input( defval = 9, minval = 1, maxval = 256, title = "EMA - Length" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, l ) =>
    r = float( 0 )
    for i = 0 to ( l-1 )
        r := ( r + s[ i ] )
    a = r / l

fEma( n, s, l ) =>
    r = float( 0 )
    r := ( na( r[ n+1 ]) ? fMa( n, s, l ) : ( r[ n+1 ] + ( 2 / ( l+1 ) ) * (s[ n ] - r[ n+1 ] ) ) )

//-------------------------------------
// PLOT

vEma                            = fEma( 0, vEmaSource, vEmaLength )
vPlotEma                        = plot( vEma, style = plot.style_line, color = color.black, title = "EMA" )

//-------------------------------------