// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-05
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.1"
vTitle                          = "Exponential Moving Average"
vShort                          = "EMA"
vOverlay                        = true
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vSource                         = input( defval = close, title = "Source" )
vLength                         = input( defval = 9, minval = 1, maxval = 1024, title = "Length" )
vSmooth                         = input( defval = 1, minval = 1, maxval = 1024, title = "Smooth" )
vOffSet                         = input( defval = 0, minval = 0, maxval = 1024, title = "Offset" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, le ) =>
    r = float( 0 )
    for i = n + 0 to ( n + ( le - 1 ) )
        r := ( r + s[ i ] )
    a = r / le

fEma( n, s, le ) =>
    ma = fMa( n, s, le )
    r = float( 0 )
    r := ( na( r[ 1 ] ) ? ma : ( r[ 1 ] + ( 2 / ( le + 1 ) ) * ( s[ n ] - r[ 1 ] ) ) )

//-------------------------------------
// COLORS

fColor( n, s ) =>
    r = ( s[ n + 1 ] < s[ n ] ) ? #26A69A : #EF5350
    r

//-------------------------------------
// PLOT

vEma                            = fMa( 0, fEma( vOffSet, vSource, vLength ), vSmooth )
vPlotEma                        = plot( vEma, style = plot.style_line, color = fColor( 0, vEma ), title = "EMA" )

//-------------------------------------