// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-04
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.0"
vTitle                          = "High - Low"
vShort                          = "HML"
vOverlay                        = false
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort+" ["+vVersion+"]", overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vHmlSmooth                      = input( defval = 9, minval = 1, maxval = 256, title = "HML - Smooth" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, l ) =>
    r = float( 0 )
    for i = 0 to ( l-1 )
        r := ( r + s[ i ] )
    a = r / l

fHml( n ) =>
    r = ( high[ n ] - low[ n ] )
    r

//-------------------------------------
// PLOT

vHighLowLine                    = fMa( 0, fHml( 0 ), vHmlSmooth )
vPlotRsi                        = plot( vHighLowLine, style = plot.style_line, color = color.black, title = "HML - Line" )

vHighLowHistogram               = fHml( 0 )
vPlotHighLow                    = plot( vHighLowHistogram, style = plot.style_columns, color = color.black, title = "HML - Histogram" )

//-------------------------------------