// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-05
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.1"
vTitle                          = "Moving Average Convergence Divergence"
vShort                          = "MACD"
vOverlay                        = false
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vMacdSource                     = input( defval = close, type = input.source, title = "MACD - Source" )
vMacdFastLength                 = input( defval = 12, minval = 1, maxval = 256, title = "MACD - Fast Length" )
vMacdSlowLength                 = input( defval = 26, minval = 1, maxval = 256, title = "MACD - Slow Length" )
vMacdSignalLength               = input( defval = 9, minval = 1, maxval = 256, title = "MACD - Signal Length" )
vMacdSmooth                     = input( defval = 1, minval = 1, maxval = 256, title = "MACD - Smooth" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, l ) =>
    r = float( 0 )
    for i = 0 to ( l-1 )
        r := ( r + s[ i ] )
    a = r / l

fMacd( n, s, lf, ls, li ) =>
	emaf = ema( s, lf )
	emas = ema( s, ls )
	macd = ( emaf - emas )
    r = macd

fSignal( macd, li ) =>
	signal = ema( macd, li )
    r = signal

fHistogram( macd, signal ) =>
	histogram = ( macd - signal )
    r = histogram

//-------------------------------------
// COLORS

fColorMacd( n, s ) =>
    r = ( s[1] > s[0] ) ? #000000 : #000001
    r

fColorSignal( n, s ) =>
    r = ( s[1] > s[0] ) ? #000000 : #000001
    r

fColorHistogram( n, s ) =>
    r = ( s >= 0 ) ? ( s[1] < s[0] ) ? #666666 : #CCCCCC : ( s[1] > s[0] ) ? #CCCCCB : #666665
    r

//-------------------------------------
// PLOT

vLineMedian                     = hline( 0, color = #666666, linestyle = hline.style_dashed, linewidth = 1, title = "Median", editable = true )

vMacd                            = fMa( 0, fMacd( 0, vMacdSource, vMacdFastLength, vMacdSlowLength, vMacdSignalLength ), vMacdSmooth )
vPlotMacd                        = plot( vMacd, style = plot.style_line, color = fColorMacd( 0, vMacd ), title = "MacD" )

vSignal                          = fMa( 0, fSignal( vMacd, vMacdSignalLength ), vMacdSmooth )
vPlotSignal                      = plot( vSignal, style = plot.style_line, color = fColorSignal( 0, vSignal ), title = "Signal" )

vHistogram                       = fHistogram( vMacd, vSignal )
vPlotHistogram                   = plot( vHistogram, style = plot.style_columns, color = fColorHistogram( 0, vHistogram ), title = "Histogram" )

//-------------------------------------
