// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-04
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.0"
vTitle                          = "Relative Strength Index"
vShort                          = "RSI"
vOverlay                        = false
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vRsiSource                      = input( defval = close, type = input.source, title = "RSI - Source" )
vRsiLength                      = input( defval = 14, minval = 1, maxval = 256, title = "RSI - Length" )
vRsiSmooth                      = input( defval = 1, minval = 1, maxval = 256, title = "RSI - Smooth" )

//-------------------------------------
// FUNCTIONS

fMaxUpDown( n, s, t ) =>
    r = ( t == 'up' ) ? max( s[ n ] - s[ n+1 ], 0 ) : max( s[ n+1 ] - s[ n ], 0 )
    r

fMa( n, s, l ) =>
    r = float( 0 )
    for i = 0 to ( l-1 )
        r := ( r + s[ i ] )
    a = r / l

fRma( n, s, l ) =>
    r = float( 0 )
    r := ( na( r[ n+1 ]) ? fMa( n, s, l ) : ( ( r[ n+1 ] * ( l-1 ) ) + s[ n ] ) / l )

fRsi( n, l, s ) =>
    r = float( 0 )
    r := ( 100 - ( 100 / ( 1 + ( fRma( n, fMaxUpDown( n, s, 'up' ), l ) / fRma( n, fMaxUpDown( n, s, 'down' ), l ) ) ) ) )

//-------------------------------------
// PLOT

vRsi                            = fMa( 0, fRsi( 0, vRsiLength, vRsiSource ), vRsiSmooth )
vPlotRsi                        = plot( vRsi, style = plot.style_line, color = color.black, title = "RSI" )

//-------------------------------------
// BANDS

vUpperBand                      = hline( 70, color = color.black, title = "RSI - Upper Band" )
vLowerBand                      = hline( 30, color = color.black, title = "RSI - Lower Band" )
fill( vUpperBand, vLowerBand, color = color.black, transp = 90, title = "RSI - Background" )

//-------------------------------------