// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-05
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.0"
vTitle                          = "Triangular Moving Average"
vShort                          = "TMA"
vOverlay                        = true
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vTmaSource                      = input( defval = close, title = "TMA - Source" )
vTmaLength                      = input( defval = 9, minval = 1, maxval = 256, title = "TMA - Length" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, l ) =>
    r = float( 0 )
    for i = 0 to ( l-1 )
        r := ( r + s[ i ] )
    a = r / l

fTma( n, s, l ) =>
    r = float( 0 )
    ma = fMa( n, s, l )
    for i = 0 to ( l-1 )
        r := ( r + ma[ i ] )
    a = r / l

//-------------------------------------
// PLOT

vTma                            = fTma( 0, vTmaSource, vTmaLength )
vPlotTma                        = plot( vTma, style = plot.style_line, color = color.black, title = "TMA" )

//-------------------------------------