// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © stmd

// @version=4

//-------------------------------------

// Release:                     2020-08-05
// Author:                      stmd
// Email:                       pine@stmd.nl
// Profile:                     https://www.tradingview.com/u/stmd/

//-------------------------------------
// PURPOSE
//

//-------------------------------------
// FEATURES
//

//-------------------------------------
// NOTES
//

//-------------------------------------
// INDICATOR PARAMETERS

vVersion                        = "V1.0"
vTitle                          = "Williams %R"
vShort                          = "W%R"
vOverlay                        = false
vScale                          = scale.right
vPrecision                      = 0

study( title = vTitle+" ["+vVersion+"]", shorttitle = vShort, overlay = vOverlay, precision = vPrecision, resolution = "" )

//-------------------------------------
// INPUTS

vWpRSource                      = input( defval = close, type = input.source, title = "W%R - Source" )
vWpRLength                      = input( defval = 10, minval = 1, maxval = 256, title = "W%R - Length" )
vWpRSmooth                      = input( defval = 1, minval = 1, maxval = 256, title = "W%R - Smooth" )

//-------------------------------------
// FUNCTIONS

fMa( n, s, l ) =>
    r = float( 0 )
    for i = 0 to ( l-1 )
        r := ( r + s[ i ] )
    a = r / l

fWpR( n, s, l ) =>
    r = float( 0 )
    r := ( ( highest( high[ n ], l ) - s[ n ] ) / ( highest( high[ n ], l ) - lowest( low[ n ], l ) ) * -100 )

//-------------------------------------
// PLOT

vWpR                            = fMa( 0, fWpR( 0, vWpRSource, vWpRLength ), vWpRSmooth )
vPlotWpR                        = plot( vWpR, style = plot.style_line, color = color.black, title = "W%R - Line" )

//-------------------------------------
// BANDS

vUpperBand                      = hline( -80, color = color.black, title = "W%R - Upper Band" )
vLowerBand                      = hline( -20, color = color.black, title = "W%R - Lower Band" )
fill( vUpperBand, vLowerBand, color = color.black, transp = 90, title = "W%R - Background" )

//-------------------------------------